baseURL = 'https://lmcj.xyz/'
languageCode = 'en-gb'
defaultContentLanguage = 'en-gb'
title = 'What is LM doing?'
theme = 'lugo'

# Header
[menu]
  [[menu.main]]
        identifier = "home"
        name = "ğŸ  Home"
        url = "/"
        weight = 1 
  [[menu.main]]
        identifier = "posts"
        name = "ğŸ““ Posts"
        url = "/posts/"
        weight = 2 
