baseURL = 'https://lmcj.xyz/'
languageCode = 'en-gb'
defaultContentLanguage = 'en-gb'
title = 'What is LM doing?'
theme = 'melange'
copyright = 'What is LM doing? Â© 2025 by Luis Mario Chaparro JÃ¡quez is licensed under CC BY-NC-SA 4.0'

[params]
	[params.author]
		email = 'webmaster@lmcj.xyz'
		name = 'Luis Mario Chaparro JÃ¡quez'

# Header
[menu]
  [[menu.main]]
        identifier = "home"
        name = "ğŸ  Home"
        url = "/"
        weight = 1 
  [[menu.main]]
        identifier = "posts"
        name = "ğŸ““ Posts"
        url = "/posts/"
        weight = 2 

[markup.highlight]
      codeFences = true
      guessSyntax = true
      hl_Lines = ""
      lineNoStart = 1
      lineNos = true
      lineNumbersInTable = false
      tabWidth = 4
      noClasses = false

[outputs]
	section = ['html', 'rss']
